// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    imagefile: 'image.bmp',
    backupfile: 'image-backup.bmp',
    use_backup: true,
    save_copy: 'copies/',
    filters: []
  };

}).call(this);
