// Generated by CoffeeScript 1.8.0
(function() {
  var Pixel;

  Pixel = require('./pixel');

  module.exports = {
    shift: {
      color: 'r',
      shift_x: 8,
      shift_y: 0,
      func: function(pixel1, p) {
        var pixel2;
        pixel2 = new Pixel(pixel1.img, pixel1.x + p.shift_x, pixel1.y + p.shift_y);
        pixel1[p.color] = pixel2[p.color];
        return pixel1.apply();
      }
    },
    pixelize: {
      step_x: 16,
      step_y: 16,
      func: function(pixel1, p) {
        var pixel2, x, y, _i, _ref, _results;
        _results = [];
        for (y = _i = 0, _ref = p.step_y - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; y = 0 <= _ref ? ++_i : --_i) {
          _results.push((function() {
            var _j, _ref1, _results1;
            _results1 = [];
            for (x = _j = 0, _ref1 = p.step_x - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; x = 0 <= _ref1 ? ++_j : --_j) {
              pixel2 = new Pixel(pixel1.img, pixel1.x + x, pixel1.y + y);
              pixel2.rgb(pixel1.rgb());
              _results1.push(pixel2.apply());
            }
            return _results1;
          })());
        }
        return _results;
      }
    },
    test: {
      func: function(pixel1, p) {
        var pixel2;
        pixel2 = new Pixel(pixel1.img, pixel1.img.width - pixel1.x, pixel1.y);
        pixel1.r = pixel2.r;
        return pixel1.apply();
      }
    }
  };

}).call(this);
