// Generated by CoffeeScript 1.8.0
(function() {
  var Pixel, floor;

  floor = Math.floor;

  Pixel = (function() {
    function Pixel(img, x, y) {
      var e, _ref, _ref1;
      this.img = img;
      this.x = x;
      this.y = y;
      this.i = this.y * this.img.width * 3 + this.x * 3;
      try {
        _ref = this.img.bmp.slice(this.i, +(this.i + 2) + 1 || 9e9), this.b = _ref[0], this.g = _ref[1], this.r = _ref[2];
      } catch (_error) {
        e = _error;
        _ref1 = [0, 0, 0], this.b = _ref1[0], this.g = _ref1[1], this.r = _ref1[2];
      }
    }

    Pixel.prototype.rgb = function(rgb) {
      if (rgb != null) {
        this.r = rgb[0], this.g = rgb[1], this.b = rgb[2];
      }
      return [this.r, this.g, this.b];
    };

    Pixel.prototype.apply = function() {
      var e, _ref, _ref1;
      try {
        return ([].splice.apply(this.img.bmp, [(_ref = this.i), (this.i + 2) - _ref + 1].concat(_ref1 = [this.b, this.g, this.r])), _ref1);
      } catch (_error) {
        e = _error;
        return [0, 0, 0];
      }
    };

    return Pixel;

  })();

  module.exports = Pixel;

}).call(this);
